# baseURL đã chính xác, giữ nguyên
baseURL = "https://dinhminh4424.github.io/BlogDinhCongMinh/"

# SỬA LỖI QUAN TRỌNG: Tắt relativeURLs để CSS/JS hoạt động đúng
relativeURLs = false
canonifyURLs = false

title = "DinhCongMinh_1916 2242"
theme = "blowfish"
defaultContentLanguage = "vi"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[params]
  customCss = ["css/custom.css"]
  customJs = ["js/custom.js"]

# SỬA LỖI CÚ PHÁP: Dùng "paginate"
[pagination]
  paginate = 6   # Số bài viết mỗi trang

[outputs]
  home = ["HTML", "RSS", "JSON"]  # JSON dùng cho search client-side

[taxonomies]
  category = "categories"
  tag = "tags"


# ----------------------------
# Menu điều hướng (Phần này đã đúng)
# ----------------------------
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Trang Chủ"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "posts"
    name = "Bài Viết"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    identifier = "categories"
    name = "Danh Mục"
    url = "/categories/"
    weight = 3

  [[menu.main]]
    identifier = "tags"
    name = "Thẻ"
    url = "/tags/"
    weight = 4



  [[menu.main]]
    identifier = "thongtin"
    name = "Thông Tin"
    url = "/profile/thong-tin"
    weight = 5